### ISSUE TITLE
UndefRefError: access to undefined reference

### ISSUE THREAD

**Issue by beamiter** [sisl/AutomotivePOMDPs.jl#16]
Sorry to tick an issue here, but I come across an annoying problem when I write my own ACC POMDP problem following your code. Here's my address: https://github.com/beamiter/julia-repo/tree/main/acc and I'll be grateful if you could take a look at it. I
construct a model and try to solve it, and fail with following hint:
  Got exception outside of a @test
  UndefRefError: access to undefined reference
  Stacktrace:
    [1] getindex
      @ ./array.jl:801 [inlined]
    [2] iterate
      @ ./array.jl:777 [inlined]
    [3] iterate
      @ ./iterators.jl:159 [inlined]
    [4] write(io::IOStream, pomdp::AccPOMDP)
      @ POMDPFiles ~/.julia/packages/POMDPFiles/vOfxh/src/write.jl:64
    [5] #3
      @ ~/.julia/packages/POMDPSolve/LzAMF/src/solver.jl:175 [inlined]
    [6] open(::POMDPSolve.var"#3#4"{AccPOMDP}, ::String, ::Vararg{String, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Base ./io.jl:330
    [7] open
      @ ./io.jl:328 [inlined]
    [8] solve(solver::POMDPSolveSolver, pomdp::AccPOMDP)
      @ POMDPSolve ~/.julia/packages/POMDPSolve/LzAMF/src/solver.jl:174
    [9] macro expansion
      @ ~/jl/acc/acc_dev.jl:556 [inlined]
   [10] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [11] top-level scope
      @ ~/jl/acc/acc_dev.jl:546
   [12] include(mod::Module, _path::String)
      @ Base ./Base.jl:386
   [13] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:285
   [14] _start()
      @ Base ./client.jl:485

**Comment by logankilpatrick** [comment]
Looks like this was resolved per: https://stackoverflow.com/questions/68279567/julia-undefreferror-access-to-undefined-reference

**Comment by MaximeBouton** [comment]
moving the discussion to SO. I will probably not have the time to update this package, you can still use it as a reference. For the automotive backend, the recent packages are
https://github.com/sisl/AutomotiveSimulator.jl
https://github.com/sisl/AutomotiveVisualization.jl

and **not** AutomotiveDrivingModels and AutoViz (which might cause errors).
